### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by ragingsmurf**
Removed VirtualEnv files. Migrated to Docker from `sh` scripts.

### CODE REVIEW

**Comment by panzertime** [comment]
The readme should say `eval $(docker-machine env findingstore)`

Also, for me at least, `docker-compose` doesn't seem to be completing.  It hung while attempting to install Elastic plugins.  I was unable to run `prep_elastic.sh`, even with changing `ELASTIC_HOST` to the "publish address" mentioned in the Elastic logs

**Comment by ragingsmurf** [comment]
The revised readme makes a reference to the `[eval](https://github.com/homedepot/dw-findingstore/pull/4/commits/f10429f1d19b79e9e3f4039cf57fc1a06c36189c#diff-04c6e90faac2675aa89e2176d2eec7d8R24)`.  

We should probably add a step about pointing `prep_elastic.sh` to the docker host's ip for processing.

**Comment by panzertime** [comment]
Created some issues.  This PR is limited to issue #5

**Comment by ragingsmurf** [comment]
@panzertime https://github.com/homedepot/dw-findingstore/pull/4/commits/fec7a507f103480a29749121b7c00540b1840d44 looks promising at resolving #5

**Comment by panzertime** [comment]
Looks good.  I've tested this and the steps all work, seems to be accessible for a developer new to the project.  I'll merge it.

**Pull request merged**
